version: '3.8'

services:
  mongo:
    image: mongo:6.0
    container_name: userdb-mongo
    ports:
      - "27017:27017"
    volumes:
      - mongo-data:/data/db
    networks:
      - user-network

  user-service:
    build: .
    container_name: user-service
    ports:
      - "5000:5000"
    depends_on:
      - mongo
    env_file:
      - .env
    networks:
      - user-network

volumes:
  mongo-data:

networks:
  user-network:
    driver: bridge
